Decision Tree

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/Defcon27/Data-Analysis-of-Indian-Automobile-dataset-using-Machine-Learning-in-R/master/indian-auto-mpg.csv', index_col = 0)

In [3]:
dataset.head()

Name Manufacturer    Location  Year  \
0            Maruti Wagon R LXI CNG       Maruti      Mumbai  2010   
1  Hyundai Creta 1.6 CRDi SX Option      Hyundai        Pune  2015   
2                      Honda Jazz V        Honda     Chennai  2011   
3                 Maruti Ertiga VDI       Maruti     Chennai  2012   
4   Audi A4 New 2.0 TDI Multitronic         Audi  Coimbatore  2013   

   Kilometers_Driven Fuel_Type Transmission Owner_Type  Engine CC   Power  \
0              72000       CNG       Manual      First        998   58.16   
1              41000    Diesel       Manual      First       1582  126.20   
2              46000    Petrol       Manual      First       1199   88.70   
3              87000    Diesel       Manual      First       1248   88.76   
4              40670    Diesel    Automatic     Second       1968  140.80   

   Seats  Mileage Km/L  Price  
0      5         26.60   1.75  
1      5         19.67  12.50  
2      5         18.20   4.50  
3      7         20.77   6.00  
4      5         15.20  17.74

In [4]:
dataset.isnull().any()

Name                 False
Manufacturer         False
Location             False
Year                 False
Kilometers_Driven    False
Fuel_Type            False
Transmission         False
Owner_Type           False
Engine CC            False
Power                False
Seats                False
Mileage Km/L         False
Price                False
dtype: bool

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5975 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Name               5975 non-null   object 
 1   Manufacturer       5975 non-null   object 
 2   Location           5975 non-null   object 
 3   Year               5975 non-null   int64  
 4   Kilometers_Driven  5975 non-null   int64  
 5   Fuel_Type          5975 non-null   object 
 6   Transmission       5975 non-null   object 
 7   Owner_Type         5975 non-null   object 
 8   Engine CC          5975 non-null   int64  
 9   Power              5975 non-null   float64
 10  Seats              5975 non-null   int64  
 11  Mileage Km/L       5975 non-null   float64
 12  Price              5975 non-null   float64
dtypes: float64(3), int64(4), object(6)
memory usage: 653.5+ KB


In [6]:
dataset = dataset.drop('Name',axis=1)
dataset = dataset.drop('Manufacturer',axis=1)
dataset = dataset.drop('Location',axis=1)


In [7]:
dataset = dataset.drop('Owner_Type',axis=1)

In [8]:
dataset = dataset.drop('Year',axis=1)

In [9]:
dataset["Fuel_Type"] = dataset["Fuel_Type"].map({'CNG': 0,'Diesel': 1,'Petrol': 2,'LPG': 3,'Electric': 4})
dataset["Transmission"] = dataset["Transmission"].map({'Manual': 0, 'Automatic': 1})

In [10]:
dataset.head()

Kilometers_Driven  Fuel_Type  Transmission  Engine CC   Power  Seats  \
0              72000          0             0        998   58.16      5   
1              41000          1             0       1582  126.20      5   
2              46000          2             0       1199   88.70      5   
3              87000          1             0       1248   88.76      7   
4              40670          1             1       1968  140.80      5   

   Mileage Km/L  Price  
0         26.60   1.75  
1         19.67  12.50  
2         18.20   4.50  
3         20.77   6.00  
4         15.20  17.74

In [11]:
data=dataset[['Kilometers_Driven','Fuel_Type','Transmission','Engine CC','Power', 'Seats', 'Price','Mileage Km/L']].values

In [12]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
data = sd.fit_transform(data)
data.shape

(5975, 8)

In [13]:
x = data[:,:-1]

In [14]:
x.shape

(5975, 7)

In [15]:
y=data[:,-1]
y.shape

(5975,)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)

In [18]:
y_train = y_train.reshape(1,-1)
y_train

array([[ 0.15494958, -1.47728017, -1.14552616, ...,  1.68544143,
        -1.3003447 ,  0.07090523]])

In [19]:
y_test = y_test.reshape(1,-1)
y_test

array([[-1.47728017e+00,  1.37580435e+00,  1.59372963e-01,
        -7.69538277e-01, -5.73729932e-02, -1.60334670e+00,
        -4.02072761e+00,  1.81489897e-01,  1.81489897e-01,
         1.64120756e+00,  4.02659240e-01,  1.81489897e-01,
        -1.35563703e+00,  1.28733661e+00, -2.60848788e-01,
        -4.29235096e-03, -3.78068540e-01,  2.08796963e+00,
         9.97604771e-01, -1.10129229e+00,  1.60582046e+00,
        -2.60848788e-01, -1.14552616e+00,  3.60637064e-01,
        -4.02397168e-01,  9.30221598e-02, -4.62112890e-01,
         9.99816465e-01,  1.72967530e+00,  9.55582596e-01,
        -5.41733854e-01,  1.55273982e+00, -1.60334670e+00,
         2.14665298e-01,  9.15772114e-01,  1.55273982e+00,
        -9.68590685e-01, -2.60848788e-01,  1.53062289e+00,
        -1.01606862e-01, -1.18976003e+00,  9.51159209e-01,
         7.18931400e-01,  1.40234467e+00, -8.39133143e-02,
         5.22090685e-01,  3.36308437e-01,  2.54475780e-01,
         4.82280203e-01,  9.30221598e-02,  2.03710068e+0

In [20]:
from sklearn.ensemble import RandomForestRegressor

In [21]:
x_train.shape

(5377, 7)

In [22]:
y_train = y_train.reshape(-1)

In [23]:
y_train

array([ 0.15494958, -1.47728017, -1.14552616, ...,  1.68544143,
       -1.3003447 ,  0.07090523])

In [24]:
rf= RandomForestRegressor(n_estimators=10,random_state=0)
rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [25]:
y_pred =rf.predict(x_test)
y_pred

array([-1.47728017e+00,  1.37580435e+00,  6.75803378e-01, -3.58384469e-01,
       -5.67831836e-01, -1.62413662e+00, -3.54410768e+00, -1.88895276e-02,
        1.48314495e-01,  1.68101804e+00, -1.28147183e-01, -1.19683745e+00,
       -1.14751668e+00,  1.38465112e+00, -2.60848788e-01, -4.29235096e-03,
       -3.78068540e-01,  2.16537890e+00,  9.97604771e-01, -2.98005238e-01,
        1.65403538e+00, -1.28147183e-01, -1.14552616e+00,  3.60637064e-01,
       -5.93708649e-01,  7.70979671e-02, -4.74203728e-02,  9.99816465e-01,
        1.65005433e+00,  8.94097519e-01, -2.95572375e-01,  1.02193340e+00,
       -1.71304669e+00,  1.74854817e-01,  9.15772114e-01,  9.60005983e-01,
       -1.49740658e+00, -4.23408255e-01,  1.79381440e+00, -4.11465111e-01,
       -1.18976003e+00,  3.99120530e-01,  7.67367486e-01,  1.47488821e+00,
        8.22438652e-01,  5.21206007e-01,  3.36308437e-01, -1.67957665e-01,
        4.82280203e-01,  5.32116781e-02,  1.67570998e+00, -3.80280233e-01,
       -1.24505236e+00, -

In [26]:
from sklearn.metrics import r2_score

In [27]:
y_test.shape
y_test = y_test.transpose()
y_test = y_test.reshape(-1)
y_test.shape


(598,)

In [28]:
accuracy = r2_score(y_test,y_pred)

In [29]:
accuracy

0.7865741873470318

In [30]:
import pickle
pickle.dump(rf,open('regression.pkl','wb'))